name: Build documentation

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

jobs:
  build:
    name: Test on ${{ matrix.label }}
    runs-on: ubuntu-24.04
    container: ghcr.io/fenics/dolfinx/dolfinx:${{ matrix.label }}
    strategy:
      fail-fast: false
      matrix:
        label: ["stable", "nightly"]
    env:
      PUBLISH_DIR: ./_build/html
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "html"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies for pyvista
        run: apt-get update && apt-get install -y libgl1-mesa-dev mesa-utils

      - name: Install dependencies
        run: |
          python3 -m pip install --check-build-dependencies --no-build-isolation ".[docs]"

      - name: Build docs
        run: jupyter book build --keep-going .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.PUBLISH_DIR }}
          name: ${{ matrix.label }}-docs
