name: Publish book

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

  # Weekly build on Mondays at 8 am
  schedule:
    - cron: "0 8 * * 1"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yml

  build-book:
    uses: ./.github/workflows/build_docs.yml

  deploy:
    runs-on: ubuntu-24.04
    needs: [build-book, run-tests]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download docs artifact
        uses: actions/download-artifact@v5
        with:
          name: stable-docs
          path: "./public"

      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./public"

      - name: Deploy coverage report to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
